---
output:
  pdf_document:
    latex_engine: xelatex
    template: template.tex
date: April 28, 2020
first: "Lucy E "
last: "Delaney"
email: "ldelan5@uic.edu"
address: "Chicago, IL 60607"
website: "ledelaney.github.io"
orcid: 
programming: "R"
languages: "$\LLaTeX$, HTML, Markdown, & Rmarkdown"
github: "ledelaney"
twitter: 
licenses: "Illinois Substitute Teaching License, FCC Technician Class Radio License"
interests: "Evolution outreach & education, macroevolution, the evolution of plant breeding systems, the nature of adaptation, `R` for data manipulation & visualization, `R` in undergraduate education"
edu:
  - {degree: PhD student, where: University of Illinois at Chicago, description_1: "in Ecology and Evolutionary Biology", description_2: "Thesis: _The Process of Natural Selection: Resultant Patterns and How We Understand Them_"}
  - {degree: MA, where: Hunter College of the City University of New York, description_1: "in Molecular and Cellular Biology"}
  - {degree: BS, where: John Jay College of the City University of New York, description_1: "in Forensic Molecular Biology, Philosophy"}
  
class:
  - {year: "2019-Present", what: "BIOS220", description_1: "Molecular and Mendelian Genetics", description_2: "Sophomore-level genetics course focusing on Mendelian inheritance patterns and molecular mechanisms of inheritance. Responsible for online transition, digital course materials, Blackboard, etc."}
  - {year: "Spring 2019", what: "BIOS230", description_1: "Ecology and Evolution", description_2: "Sophomore-level course with emphasis on basic ecological systems and ecosystem dynamics, and evolutionary principles. Responsible for weekly office hours and assignment construction and grading."}
  - {year: 2017-2018, what: "BIOS430", description_1: "Evolution", description_2: "Upper-division, programming-focused Evolution course."}
  - {year: 2016-2017, what: "BIOS120", description_1: "Biology of Populations and Communities", description_2: "Introductory biology laboratory course with emphasis on ecological and evolutionary principles."}

work:
  - {year: "2018-Present", where: "at Nurturing Wisdom Tutoring", what: "Tutor", description: "Highly-rated individual tutoring for grades 7-12 in science, mathematics, reading, language, and writing. Provide tutoring of content and test-preparation strategies for High School Entrance Exams and SATs."}
  - {year: 2012-2015, where: "at NYC Office of Chief Medical Examiner", what: "Forensic Molecular Biologist", description: "Examined evidence for the presence of biological fluids, performed serological and DNA analysis techniques, analyzed data and performed statistical analysis, wrote reports, and provided expert scientific testimony in court."}
  - {year: 2011-2012, where: "at NYC Deptartment of Health", what: "Health Research Intern", description: "Accepted to the Health Research Training Program for a year-long internship with the Bureau of Environmental Disease Prevention. Received training in disease epidemiology, emergency preparedness and response, public health and outreach programs in environmental disease control and prevention, and emerging viral infections."}
  - {year: 2008-2011, where: "at Working Families Party", what: "Field Manager & Administrative Assistant", description: "Performed administrative tasks including payroll, managing employees' healthcare coverage, bank deposits, and data entry. Organized informational events for the public, and served as Field Manager for multiple election and fundraising campaigns."}
  
extra:
  - {year: 2018, name: "Recipient of the Graduate Teaching Award"}
  - {year: 2017, name: "Accepted to MicroMORPH summer course at Harvard University"}
  - {year: 2017, name: "Volunteer at Garfield Park Conservatory"}
  
bibliography: mypapers.bib
csl: apa.csl
nocite: '@*'

---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library("tidyverse")
setwd("/Users/lucydelaney/rmd-cv/")

```

# Extracurricular

# Presentations
\vspace{-0.05cm}

```{r, eval = T, echo = FALSE, message = FALSE, warning = FALSE}
presentations <- read_csv(file = "presentations.csv", col_names = T, na = c(NA, "", " "), trim_ws = T, skip_empty_rows = T) %>%
  arrange(invited, desc(when))

```

```{r, eval = T, results = "asis", message = FALSE, warning = FALSE, echo = FALSE}
not.invited <- presentations %>%
  filter(invited == 0) %>%
  arrange(-when)
glue::glue_data(not.invited, "**>where<** >what< \\fn{>when<}",
                "\\begin{quote}>gsub('\\\\*', '', who)<, \\href{>link<}{\">title<.\"}\\end{quote}",
                .open = ">", .close = "<")
```

# Publications
\vspace{-0.05cm}

