---
title: "Untitled"
output:
  pdf_document:
    keep_tex: true
    template: template.tex
    latex_engine: xelatex
---

<!-- %%%------------------------------------------------------------------------ -->
<!-- %%% Address and contact block -->
<!-- %%%------------------------------------------------------------------------ -->

\noindent
\begin{minipage}{.65\textwidth}
\vspace{1mm}
  {\footnotesize \noindent{\LARGE \textsc{lucy delaney}}\\ \href{http://bios.uic.edu}{Department of Biological Sciences} \\ University of Illinois at Chicago \\ \vspace{-0.05in} Chicago, \textsc{il} 60622}
\end{minipage}
\hfill
\begin{minipage}{.65\textwidth}
{\footnotesize \faPhone \ \myphone} \\
{\scriptsize \faTwitter \  \texttt{\href{http://twitter.com/emergentylucy}{\mytwitter}}}\\
{\scriptsize \faEnvelope \  \texttt{\href{mailto:\myemail}{\myemail}}}\\
{\scriptsize \faGithub \ \texttt{\href{\myweb}{\myweb}}}


\end{minipage}


\bigskip       
\reversemarginpar

\bigskip       


<!-- %% Appointments -->
<!-- % \medskip -->
\marginhead{\sffamily \textbf{\textcolor{maroon}{education}}}

\ind PhD candidate in Evolutionary Biology, 2016--Present.      

\ind Visiting Associate Professor of Sociology, Duke University, 2008--2009.

\ind Associate Professor of Sociology, University of Arizona, 2008.

\ind Research Fellow, Social and Political Theory Program,
Research School of Social Sciences, Australian National University, 2003--2006.

\ind Assistant Professor of Sociology, University of Arizona, 2001--2008.

\bigskip

<!-- %% Education -->

\marginhead{\sffamily {{\vskip -0.23em} education}}

\ind Ph.D, Sociology, Princeton University, 2001.

\ind \hspace{0.35in} \footnotesize Dissertation: \emph{Exchange in Blood and Organs}.\newline Winner, American Sociological Association's Dissertation Award.\normalsize \vspace{0.05in}

\ind M.A., Sociology, Princeton University, 1998. 

\ind M.A., Sociology, First Class, National University of Ireland (Cork), 1994.

\ind \hspace{0.35in} \footnotesize Thesis: \emph{The Language of Influence: Public Debate and the Politics of the X-case.} \normalsize \vspace{0.01in}

\ind B.A. (Joint Hons.), First Class, National University of Ireland (Cork), 1993.

\bigskip
 
<!-- %% Publications -->
\marginhead{\sffamily {\vskip 0.35em} publications}
\medskip
\noindent\emph{Book \vspace{0.01in}}

\ind  Kieran Healy. 2006. \emph{\href{http://www.lastbestgifts.com}{Last Best Gifts: Altruism and the Market for Human Blood and Organs}}. Chicago:~University of Chicago Press. \vspace{0.05in}

\ind \hspace{0.35in} \footnotesize Winner, Association for Research on Nonprofit Organizations and Voluntary Action (ARNOVA) Outstanding Book Prize. Finalist, C. Wright Mills Award. 

\vspace{-0.075in}

\normalsize

\bigskip
\noindent\emph{Journal articles \vspace{0.05in}}

\ind Forthcoming. Kieran Healy and James Moody. ``Data Visualization in Sociology.'' \emph{Annual Review of Sociology.}

\ind Marion Fourcade and Kieran Healy. 2013. ``\href{http://kieranhealy.org/files/papers/classification-situations.pdf}{Classification Situations: Life-chances in the Neoliberal Era}.'' \emph{Accounting, Organizations, and Society} 38:~559--572.

\ind Kieran Healy and Kimberly R. Krawiec. 2012. ``\href{http://kieranhealy.org/files/papers/custom-contract-kidney.pdf}{Custom, Contract, and Kidney Exchange}.'' \emph{Duke Law Journal} 62:~645--670. 

\ind Kieran Healy. 2011. ``Counting and Commodifying.'' \emph{Washington University Journal of Law and Policy}. 35:~337--347.


<!-- %\newpage -->
\noindent\emph{Essays and reviews \vspace{0.05in}}

<!-- %\renewcommand{\labelenumi}{\textsc{r}\theenumi.} -->
<!-- %\begin{revnumerate} -->

\ind Kieran Healy. 2011. ``\href{http://www.kieranhealy.org/files/reviews/karpik-review.pdf}{Judgment and Distinction}.'' \emph{Socio--Economic Review} 9:~787--800. 

\ind Kieran Healy. 2011. ``\href{http://polmeth.wustl.edu/methodologist/tpm_v18_n2.pdf}{Choosing your Workflow Applications}.'' \emph{The Political Methodologist} 18 (2):~9--18. 


\bigskip

<!-- %\newpage -->

\marginhead{\sffamily {\vskip 0.5em}selected \newline conference \newline presentations \newline since 2007}
\medskip

\ind ``Dealing with Awkward Relations.'' Conference on New Theoretical Directions in Economic Sociology, Stockholm, September 2013. 

\ind ``Credit Scores and the Moralization of Inequality.'' Annual Meetings of the American Sociological Association, New York, August 2013.
 
\bigskip

\marginhead{\sffamily {\vskip 0.6em}grants,\newline honors, \newline \& awards}
\medskip

\ind Residential Fellowship, Center for Advanced Study in the Behavioral Sciences, Stanford University, 2008-09.

\ind Association for Research on Nonprofit Organizations and Voluntary Action (ARNOVA) Outstanding Book Prize, 2007.

\ind Finalist, Society for the Study of Social Problems (SSSP), C. Wright Mills Award, 2007.

\ind Rogers Program in Law and Society, Faculty Research Award, University of Arizona, 2006.

\ind Participant, Summer Institute on \emph{Economy and Society: Trajectories of Capitalism}, Center for Advanced Study in the Behavioral Sciences, 2006.

\ind University of Arizona SBSRI/Center for Applied Spatial
Analysis. Geographical Information Systems Research Assistance
Program Award. ``The Geography of Organ Procurement'', 2003.




\marginhead{\sffamily {\vskip 1.12em}service to the \newline profession}
\medskip

\medskip


\marginhead{{\vskip 0.9em}Service to the \newline Profession}
\medskip

\medskip

